import type { AvailablePlatformKey } from "@shared/availablePlatforms";

export interface AppIdea {
  idea: string;
  integrations: string[];
  platform: AvailablePlatformKey;
}

export const appIdeas: AppIdea[] = [
  {
    "idea": "A platform that connects users with personalized travel itineraries generated by an AI, with options for booking flights and accommodations.",
    "platform": "website",
    "integrations": ["api", "auth", "billing", "database", "email", "llm", "maps"]
  },
  {
    "idea": "A collaborative storytelling website where users can contribute to a story and vote on the direction of the plot.",
    "platform": "website",
    "integrations": ["auth", "database", "realtime"]
  },
  {
    "idea": "An e-commerce site for sustainable and ethically sourced products, with a feature that calculates the carbon footprint of each purchase.",
    "platform": "website",
    "integrations": ["analytics", "api", "billing", "database", "email", "payments"]
  },
  {
    "idea": "A language learning app that uses augmented reality to translate objects in the real world.",
    "platform": "mobile-app",
    "integrations": ["api", "llm"]
  },
  {
    "idea": "A meditation app that creates personalized soundscapes based on the user's heart rate and breathing patterns.",
    "platform": "mobile-app",
    "integrations": ["analytics", "api", "database",  "llm"]
  },
  {
    "idea": "A social networking app for pet owners, with features for sharing photos, organizing playdates, and finding pet-friendly locations.",
    "platform": "mobile-app",
    "integrations": ["auth", "database", "maps", "realtime", "uploads"]
  },
  {
    "idea": "A code editor with a built-in AI assistant that can debug code, suggest optimizations, and generate documentation.",
    "platform": "desktop-app",
    "integrations": ["api", "files", "llm", "realtime"]
  },
  {
    "idea": "A project management tool that uses a kanban board interface and integrates with popular version control systems.",
    "platform": "desktop-app",
    "integrations": ["api", "database", "realtime"]
  },
  {
    "idea": "A digital art application that allows users to create and sell their own NFTs.",
    "platform": "desktop-app",
    "integrations": ["api", "billing", "database", "files", "payments", "uploads"]
  },
  {
    "idea": "AI-powered recipe generator based on ingredients you have at home.",
    "platform": "website",
    "integrations": ["api", "database", "llm", "uploads"]
  },
  {
    "idea": "Personalized workout plan generator with video demonstrations.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "llm", "payments", "uploads"]
  },
  {
    "idea": "A platform for local artists to sell their work and host virtual galleries.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "payments", "realtime", "uploads"]
  },
  {
    "idea": "A subscription box service for artisanal coffee from around the world.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "payments"]
  },
  {
    "idea": "A website that helps users find and book appointments with local service providers.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "maps", "payments"]
  },
  {
    "idea": "An online platform for creating and sharing interactive fiction.",
    "platform": "website",
    "integrations": ["auth", "database", "realtime"]
  },
  {
    "idea": "A tool for generating and managing legal documents for small businesses.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "files", "llm", "payments"]
  },
  {
    "idea": "A marketplace for sustainable and zero-waste products.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "payments", "uploads"]
  },
  {
    "idea": "A platform for connecting language learners with native speakers for conversation practice.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "payments", "realtime"]
  },
  {
    "idea": "A website for creating and sharing custom digital escape rooms.",
    "platform": "website",
    "integrations": ["auth", "database", "payments", "realtime"]
  },
  {
    "idea": "A tool for visualizing and analyzing stock market data.",
    "platform": "website",
    "integrations": ["api", "database", "realtime"]
  },
  {
    "idea": "A platform for organizing and managing online coding bootcamps.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "payments", "realtime", "uploads"]
  },
  {
    "idea": "A website for discovering and booking unique travel experiences.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "maps", "payments", "uploads"]
  },
  {
    "idea": "A tool for creating and sending personalized video messages.",
    "platform": "website",
    "integrations": ["auth", "database", "email", "uploads"]
  },
  {
    "idea": "A platform for hosting and participating in online debates.",
    "platform": "website",
    "integrations": ["auth", "database", "realtime"]
  },
  {
    "idea": "A website for finding and adopting pets from local shelters.",
    "platform": "website",
    "integrations": ["auth", "database", "email", "maps", "uploads"]
  },
  {
    "idea": "A tool for creating and managing online courses.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "payments", "uploads"]
  },
  {
    "idea": "A plant identification app that also provides care instructions.",
    "platform": "mobile-app",
    "integrations": ["api", "database", "llm-image", "uploads"]
  },
  {
    "idea": "A mobile game that teaches users how to code.",
    "platform": "mobile-app",
    "integrations": ["analytics", "auth", "database", "realtime"]
  },
  {
    "idea": "A social media app for sharing and discovering new music.",
    "platform": "mobile-app",
    "integrations": ["api", "auth", "database", "realtime", "uploads"]
  },
  {
    "idea": "A personal safety app that sends alerts to emergency contacts.",
    "platform": "mobile-app",
    "integrations": ["api", "auth", "database", "maps", "sms"]
  },
  {
    "idea": "A mobile wallet for managing and spending cryptocurrency.",
    "platform": "mobile-app",
    "integrations": ["api", "auth", "billing", "database", "payments"]
  },
  {
    "idea": "An app for finding and booking last-minute restaurant reservations.",
    "platform": "mobile-app",
    "integrations": ["api", "auth", "billing", "database", "maps", "payments", "realtime"]
  },
  {
    "idea": "A guided meditation app with customizable soundscapes.",
    "platform": "mobile-app",
    "integrations": ["analytics", "auth", "database",  "llm"]
  },
  {
    "idea": "A mobile app for tracking and managing personal finances.",
    "platform": "mobile-app",
    "integrations": ["analytics", "api", "auth", "database", "uploads"]
  },
  {
    "idea": "A tool for creating and sharing short-form video content.",
    "platform": "mobile-app",
    "integrations": ["api", "auth", "database", "realtime", "uploads"]
  },
  {
    "idea": "An app for learning a new instrument with interactive lessons.",
    "platform": "mobile-app",
    "integrations": ["analytics", "api", "auth", "database", "llm", "realtime"]
  },
  {
    "idea": "A mobile app for ordering and delivering groceries.",
    "platform": "mobile-app",
    "integrations": ["api", "auth", "billing", "database", "maps", "payments"]
  },
  {
    "idea": "A tool for scanning and digitizing old photos.",
    "platform": "mobile-app",
    "integrations": ["api", "auth", "database", "llm-image", "uploads"]
  },
  {
    "idea": "An app for finding and connecting with local volunteer opportunities.",
    "platform": "mobile-app",
    "integrations": ["api", "auth", "database", "maps"]
  },
  {
    "idea": "A mobile game that uses augmented reality to create a virtual pet.",
    "platform": "mobile-app",
    "integrations": ["analytics", "api", "auth", "database", "llm", "realtime"]
  },
  {
    "idea": "An app for tracking and managing chronic health conditions.",
    "platform": "mobile-app",
    "integrations": ["analytics", "api", "auth", "database"]
  },
  {
    "idea": "A tool for creating and sharing custom workout routines.",
    "platform": "mobile-app",
    "integrations": ["analytics", "auth", "database", "uploads"]
  },
  {
    "idea": "A mobile app for learning and practicing calligraphy.",
    "platform": "mobile-app",
    "integrations": ["analytics", "database", "uploads"]
  },
  {
    "idea": "A desktop client for managing multiple email accounts.",
    "platform": "desktop-app",
    "integrations": ["api", "database", "email"]
  },
  {
    "idea": "A tool for creating and editing professional-quality videos.",
    "platform": "desktop-app",
    "integrations": ["api", "files", "llm", "uploads"]
  },
  {
    "idea": "A desktop app for organizing and managing research papers.",
    "platform": "desktop-app",
    "integrations": ["api", "database", "files", "llm"]
  },
  {
    "idea": "A password manager that securely stores and autofills login credentials.",
    "platform": "desktop-app",
    "integrations": ["api", "database", "files"]
  },
  {
    "idea": "A desktop app for creating and editing 3D models.",
    "platform": "desktop-app",
    "integrations": ["api", "files", "uploads"]
  },
  {
    "idea": "A tool for managing and organizing large photo libraries.",
    "platform": "desktop-app",
    "integrations": ["api", "database", "files", "llm-image", "uploads"]
  },
  {
    "idea": "A desktop app for writing and formatting screenplays.",
    "platform": "desktop-app",
    "integrations": ["database", "files", "llm"]
  },
  {
    "idea": "A tool for creating and managing virtual machines.",
    "platform": "desktop-app",
    "integrations": ["api", "files"]
  },
  {
    "idea": "A desktop app for composing and producing music.",
    "platform": "desktop-app",
    "integrations": ["api", "files", "uploads"]
  },
  {
    "idea": "A tool for analyzing and visualizing large datasets.",
    "platform": "desktop-app",
    "integrations": ["api", "database", "files"]
  },
  {
    "idea": "A desktop app for creating and editing vector graphics.",
    "platform": "desktop-app",
    "integrations": ["files", "uploads"]
  },
  {
    "idea": "A tool for managing and synchronizing files across multiple devices.",
    "platform": "desktop-app",
    "integrations": ["api", "database", "files", "realtime"]
  },
  {
    "idea": "A desktop app for taking and organizing notes.",
    "platform": "desktop-app",
    "integrations": ["database", "files", "llm", "uploads"]
  },
  {
    "idea": "A tool for creating and managing personal budgets.",
    "platform": "desktop-app",
    "integrations": ["analytics", "database", "files"]
  },
  {
    "idea": "A desktop app for learning and practicing touch typing.",
    "platform": "desktop-app",
    "integrations": ["analytics", "database"]
  },
  {
    "idea": "A tool for creating and editing podcasts.",
    "platform": "desktop-app",
    "integrations": ["api", "files", "uploads"]
  },
  {
    "idea": "A B2B SaaS platform for managing teams and projects within an organization.",
    "platform": "website",
    "integrations": ["auth", "billing", "database", "email", "organizations", "payments"]
  },
  {
    "idea": "A tool to scan invoices and receipts to automatically extract structured data for expense tracking.",
    "platform": "website",
    "integrations": ["uploads", "llm-json", "database", "auth", "email"]
  },
  {
    "idea": "A collaborative online whiteboard for teams to brainstorm and share ideas in real-time.",
    "platform": "website",
    "integrations": ["whiteboard", "realtime", "auth", "database", "uploads", "files"]
  },
  {
    "idea": "A secure cloud storage platform for personal and business use with file versioning.",
    "platform": "desktop-app",
    "integrations": ["files", "auth", "database", "uploads", "organizations"]
  },
  {
    "idea": "An appointment reminder system that sends SMS alerts to clients.",
    "platform": "website",
    "integrations": ["sms", "database", "auth", "billing", "payments"]
  }
]

export default appIdeas;

